kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-access
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view-access
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webfull-rb-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-full-access
subjects:
- kind: User
  namespace: web
  name: "3ea5be38-c654-4108-932d-4292d19e3c25"


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apiread-rb-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-view-access
subjects:
- kind: Group
  namespace: api
  name: "89cace2e-d62f-4775-95f2-434c4cfcfeb6"


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apifull-rb-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-full-access
subjects:
- kind: Group
  namespace: api
  name: "89cace2e-d62f-4775-95f2-434c4cfcfeb6"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webread-rb-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-view-access
subjects:
- kind: User
  namespace: web
  name: "ac38a1ba-4791-4241-b85d-741ffddd7fa9"