apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile
  labels:
    app: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registryacs2871.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
          name: user-profile
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: SQL_DBNAME